services:
  web:
    build:
    context: .
    container_name: analog-youtube-web
    ports:
      - "8000:8000"
    restart: unless-stopped
    
  scanner:
    build: .
    container_name: analog-youtube-scanner
    command: python src/qr_listener/listener.py
    restart: unless-stopped

    devices:
    - /dev/input:/dev/input
    
    environment:
      PLAY_ENDPOINT: http://web:8000/api/play
    
    depends_on:
      - web
  