services:
  analog-youtube:
    build:
      context: .
      dockerfile: Dockerfile
      ports:
        - "8000:8000"
    
    container_name: analog-youtube

    ports:
    - "8000:8000"

    environment:
      PUBLIC_BASE_URL: http://analog-youtube.local:8000
      PRIVATE_BASE_URL: http://localhost:8000
    
    volumes:

    restart: unless-stopped
  